### ISSUE TITLE
Geopack.trace not providing vector of output values

### ISSUE THREAD

**Issue by w2ruf** [tsssss/geopack#1]
Hi,

I am trying to do a field line trace and get the points for the entire field line. However, I am only getting a single set of coordinates even though the [documentation for the function](https://github.com/tsssss/geopack/blob/56f16f046f66ae9882e784647de13f6426d47e97/geopack/geopack.py#L1122-L1125) says it should also output a vector of coordinates. Could you please help?

Example Code: 
`geopack.trace(1,0,.5, 1,10,1,2,'t89','igrf')`

Output:
`(0.9921003911113675, 0.00048052726154043516, 0.1254269006978363)`

Thank you!

**Comment by tsssss** [comment]
Hello, I just made trace to return the field lines as well. I haven't had the setup at hand to test. So could you please verify if the change works? BTW: Thanks for catching this! -Sheng

**Comment by w2naf** [comment]
Hi Sheng,

Thanks for your help on this! There was another small bug, but I fixed it in https://github.com/tsssss/geopack/pull/2, added a keyword for maxloop, and created a notebook demonstrating field line tracing.

Best,
Nathaniel
