### ISSUE TITLE
Releasing new version to PyPI?

### ISSUE THREAD

**Issue by supervised** [tsssss/geopack#10]
Hello!

I ran into some differences with T96 while comparing the results to IDL; to fix the problems, I updated to the GitHub release with:

`pip install https://github.com/tsssss/geopack/archive/master.zip`

instead of using:

`pip install geopack`

So I think the last T96 bug fix hasn't made it to a release on PyPI yet. 

Are there plans to do a new release soon?

Thanks in advance!

**Comment by tsssss** [comment]
Thanks for reminding me! A new version with t96 fixed has been uploaded to PyPI.
