### ISSUE TITLE
Bug report on t96.py

### ISSUE THREAD

**Issue by madokatext** [tsssss/geopack#18]
Hello! I found that the func t96 of geopack python version has very different results with the IDL version at some places, such as dayside magnetosphere. But at other places, they get exactly the same results. I began to doubt some parts of the codes have some problems.

After long time of debugging, I found two bugs:
1. t96.py: func r2_birk: line 1410: "r2outer" should be "r2sheet".
2. t96.py: func birk1tot_02: line 844: "[x1,y1,z1,ps]" should be "[x2,y2,z2,ps]".

The IDL version of geopack is directly compiled from the original FORTRAN77 codes, so I think its results are correct.
I diecrtly compared the FORTRAN77 codes with the python codes, and found the two bugs above.

**Comment by madokatext** [comment]
3. t96.py: func birk1tot_02: line 731: "&" should be "|".

**Comment by tsssss** [comment]
Thanks for catching the bugs. That's really helpful since I mostly use it in the nightside. Should I wait until you are done with debugging t96 then update the package?



________________________________

**Comment by madokatext** [comment]
I think you can update it right now. I haven't met problems using the package after that.

**Comment by jameswilburlewis** [comment]
Thanks @madokatext!  With that additional fix, the results match to within 0.25 nT near perigee, and a relative tolerance of .001 everywhere.   

![t96_diffs](https://github.com/tsssss/geopack/assets/105754292/f98d9251-6b24-4599-a620-2824ad688592)
