### ISSUE TITLE
inconsistent comparison results

### ISSUE THREAD

**Issue by shihikoo** [tsssss/geopack#7]
Hi 

I'm testing this python geopack package with the IDL routine.

I first tested with the parameters used in the test_geopack1.md as following:
Time/dipole tilt: 2001-01-01/02:03:04 UT/ps = -0.533585131 rad
Position: (xgsm,ygsm,zgsm) = (-5.1,0.3,2.8)
Model parameter:
T89: iopt = 2
T96, T01, and T04: par = [2., -87., 2., -5., 0., 0., ps, xgsm,ygsm,zgsm].

t89    | idl | 20.772 | -0.647 | -15.072
  | python | 20.772 | -0.647 | -15.072
t96    | idl | 61.179 | -1.461 | -40.451
  | python | 61.179 | -1.461 | -40.451
t01    | idl | 46.973 | 1.544 | -31.355
  | python | 46.354 | 1.440 | -32.000
t04    | idl | -8.080 | -1.512 | -0.722
  | python | 12.010 | -2.635 | -11.964

This result is similar to what is in  test_geopack1.md except t04 for IDL routine. 

I then tested for one of the MMS data, and the results are much different
datetime | 2016-01-01/12:13:20
iopt / kp | 3 / 2
(xgsm,ygsm,zgsm) = | 6.96, 0.49,  -0.66
parmod | 0.976, -50.20, 6.59, -5.512, 0., 0., tilt, x,y,z

t89    | idl | -3.657066785 | 1.085712758 | 13.86057416
  | python | -2.37842015 | 1.038191716 | 14.38198039

t96    | idl | 22.97810632 | -1.106448782 | -4.147864164
  | python | 50.00624944 | 6.397909797 | -147.0215389

t01    | idl | 5.001211425 | 0.02607965332 | 3.264103442
  | python | 6.230733691 | 4.283414418 | -2.58591528

t04    | idl | -15.25291193 | -8.650237035 | -10.97633666
  | python | 7.905332371 | -1.161844446 | -7.933264503

Could you help me with it? 

Thanks

**Comment by tsssss** [comment]
Hello,

It looks like you got two questions here:
1. The IDL results for t04 are not the same as those in the example.
2. In the MMS example, IDL and python results do not compare in essentially
all models.

Let's solve #1 first. Are you running the example with par =
[2,-87,2,-5,0,0, tilt, x,y,z], where the tilt is in radian?

Thanks,
Sheng

**Comment by tsssss** [comment]
Hello,

I'll close this issue because I've tested that if tilt in radian is used, the IDL results for t04 are the same as those in the example. For Bx,y,z, I got
       12.009596      -2.6345863      -11.964033

Please feel free to test your MMS example and contact me if there's still inconsistency.

Thanks,
Sheng
