### ISSUE TITLE
some errors in t96.py

### ISSUE THREAD

**Issue by shanqiangchen** [tsssss/geopack#8]
Maybe there are some errors in t96.py?
one error with BIRK1TOT_02 fuction in t96.py,  should change c2[54]=29.2043 to c2[54]=-29.2043;
one error with condip1(xi) fuction in t96.py,should change if (i == 2) | (i == 4) | (i == 6): to if (i == 2) | (i == 4) | (i == 5):

**Comment by tsssss** [comment]
Hello,

Thank you so much! I'll implement them this weekend.
BTW: Have you found any other typos?

Sheng

**Comment by tsssss** [comment]
Done. Thanks!
